apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
  version: v1.0
  labels:
    app: mgmt-app
spec:
  selector:
    matchLabels:
      app: mgmt-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mgmt-app
        tier: frontend
    spec:
      containers:
      - image: hufsie96/management
        imagePullPolicy: Always
        name: management
        env:
        - name: MYSQL_HOST
          value: mgmt-mysql
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mgmt-mysql-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mgmt-mysql-pass
              key: password
        ports:
        - containerPort: 8080
          name: management
---
apiVersion: v1
kind: Service
metadata:
  name: management
  version: v1.0
  labels:
    app: mgmt-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mgmt-app
    tier: frontend
  type: ClusterIP
