apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mgmt-app"},"name":"management","namespace":"default"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"app":"mgmt-app","tier":"frontend"},"type":"LoadBalancer"}}
  labels:
    discovered_by: kubernetesplugin
    service: management
  name: default-management-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      app: mgmt-app
  kube:
    selector:
      app: mgmt-app
      tier: frontend
    serviceName: management
    serviceNamespace: default
    servicePort: 8080
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://management:8080/v2/api-docs
